title: Jose Valentin Osuna Enciso # your name (or website title) here
logo: "/images/vale.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science and Analytics professional with 8+ years of experience in statistical data analysis, data management, and data visualization techniques, with strong 
  problem-solving and analytical skills, as well as proficient domain knowledge in sales, service, and academia.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/valentin-osuna-enciso/">My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-V7HNYG4LHV # your Google Analytics tracking ID here
