title: Jose Valentin Osuna Enciso # your name (or website title) here
logo: "/images/vale.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science and Machine Learning professional with 12+ years of experience in data analysis, data management, 
  data visualization techniques, statistical modeling, and algorithm development, with strong 
  problem-solving and analytical skills, as well as proficient domain knowledge in sales, service, and academia.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/valentin-osuna-enciso/">My LinkedIn Profile</a> 
  <br>
  <a href="https://scholar.google.ca/citations?user=u_oHCUUAAAAJ&hl=fr">My Google Scholar Profile</a> 
  <br>
  <a href="https://www.researchgate.net/profile/Valentin-Osuna-Enciso">My ResearchGate Profile</a> 
  <br>
  <a href="https://orcid.org/0000-0001-6844-9013">My Orcid Profile</a> 
  <br>
  <a href="https://www.webofscience.com/wos/author/record/3943888">My Web of Science Profile</a> 
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-V7HNYG4LHV # your Google Analytics tracking ID here
